apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      tier: frontend
  template:
    metadata:
      labels:
        app: order
        tier: frontend
    spec:
      containers:
      - name: order
        image: aankitatiwari24/air-pg:order
        ports:
        - containerPort: 5000
