apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      tier: frontend
  template:
    metadata:
      labels:
        app: user
        tier: frontend
    spec:
      containers:
      - name: user
        image: aankitatiwari24/air-pg:user
        ports:
        - containerPort: 5000
